/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PrayerSectionService } from "../prayerSection.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PrayerSectionCreateInput } from "./PrayerSectionCreateInput";
import { PrayerSection } from "./PrayerSection";
import { PrayerSectionFindManyArgs } from "./PrayerSectionFindManyArgs";
import { PrayerSectionWhereUniqueInput } from "./PrayerSectionWhereUniqueInput";
import { PrayerSectionUpdateInput } from "./PrayerSectionUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PrayerSectionControllerBase {
  constructor(
    protected readonly service: PrayerSectionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PrayerSection })
  @nestAccessControl.UseRoles({
    resource: "PrayerSection",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPrayerSection(
    @common.Body() data: PrayerSectionCreateInput
  ): Promise<PrayerSection> {
    return await this.service.createPrayerSection({
      data: data,
      select: {
        createdAt: true,
        dailyPrayerTheme: true,
        id: true,
        prayerCommitment: true,
        prayerEvent: true,
        prayerGroup: true,
        prayerRequest: true,
        testimony: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [PrayerSection] })
  @ApiNestedQuery(PrayerSectionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PrayerSection",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async prayerSections(
    @common.Req() request: Request
  ): Promise<PrayerSection[]> {
    const args = plainToClass(PrayerSectionFindManyArgs, request.query);
    return this.service.prayerSections({
      ...args,
      select: {
        createdAt: true,
        dailyPrayerTheme: true,
        id: true,
        prayerCommitment: true,
        prayerEvent: true,
        prayerGroup: true,
        prayerRequest: true,
        testimony: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PrayerSection })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PrayerSection",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async prayerSection(
    @common.Param() params: PrayerSectionWhereUniqueInput
  ): Promise<PrayerSection | null> {
    const result = await this.service.prayerSection({
      where: params,
      select: {
        createdAt: true,
        dailyPrayerTheme: true,
        id: true,
        prayerCommitment: true,
        prayerEvent: true,
        prayerGroup: true,
        prayerRequest: true,
        testimony: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PrayerSection })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PrayerSection",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePrayerSection(
    @common.Param() params: PrayerSectionWhereUniqueInput,
    @common.Body() data: PrayerSectionUpdateInput
  ): Promise<PrayerSection | null> {
    try {
      return await this.service.updatePrayerSection({
        where: params,
        data: data,
        select: {
          createdAt: true,
          dailyPrayerTheme: true,
          id: true,
          prayerCommitment: true,
          prayerEvent: true,
          prayerGroup: true,
          prayerRequest: true,
          testimony: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PrayerSection })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PrayerSection",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePrayerSection(
    @common.Param() params: PrayerSectionWhereUniqueInput
  ): Promise<PrayerSection | null> {
    try {
      return await this.service.deletePrayerSection({
        where: params,
        select: {
          createdAt: true,
          dailyPrayerTheme: true,
          id: true,
          prayerCommitment: true,
          prayerEvent: true,
          prayerGroup: true,
          prayerRequest: true,
          testimony: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
