/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CommunitySection } from "./CommunitySection";
import { CommunitySectionCountArgs } from "./CommunitySectionCountArgs";
import { CommunitySectionFindManyArgs } from "./CommunitySectionFindManyArgs";
import { CommunitySectionFindUniqueArgs } from "./CommunitySectionFindUniqueArgs";
import { DeleteCommunitySectionArgs } from "./DeleteCommunitySectionArgs";
import { CommunitySectionService } from "../communitySection.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => CommunitySection)
export class CommunitySectionResolverBase {
  constructor(
    protected readonly service: CommunitySectionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "CommunitySection",
    action: "read",
    possession: "any",
  })
  async _communitySectionsMeta(
    @graphql.Args() args: CommunitySectionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [CommunitySection])
  @nestAccessControl.UseRoles({
    resource: "CommunitySection",
    action: "read",
    possession: "any",
  })
  async communitySections(
    @graphql.Args() args: CommunitySectionFindManyArgs
  ): Promise<CommunitySection[]> {
    return this.service.communitySections(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => CommunitySection, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "CommunitySection",
    action: "read",
    possession: "own",
  })
  async communitySection(
    @graphql.Args() args: CommunitySectionFindUniqueArgs
  ): Promise<CommunitySection | null> {
    const result = await this.service.communitySection(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => CommunitySection)
  @nestAccessControl.UseRoles({
    resource: "CommunitySection",
    action: "delete",
    possession: "any",
  })
  async deleteCommunitySection(
    @graphql.Args() args: DeleteCommunitySectionArgs
  ): Promise<CommunitySection | null> {
    try {
      return await this.service.deleteCommunitySection(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
