/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  EvangelismSection as PrismaEvangelismSection,
} from "@prisma/client";

export class EvangelismSectionServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.EvangelismSectionCountArgs, "select">
  ): Promise<number> {
    return this.prisma.evangelismSection.count(args);
  }

  async evangelismSections<T extends Prisma.EvangelismSectionFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.EvangelismSectionFindManyArgs>
  ): Promise<PrismaEvangelismSection[]> {
    return this.prisma.evangelismSection.findMany<Prisma.EvangelismSectionFindManyArgs>(
      args
    );
  }
  async evangelismSection<T extends Prisma.EvangelismSectionFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.EvangelismSectionFindUniqueArgs>
  ): Promise<PrismaEvangelismSection | null> {
    return this.prisma.evangelismSection.findUnique(args);
  }
  async createEvangelismSection<T extends Prisma.EvangelismSectionCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.EvangelismSectionCreateArgs>
  ): Promise<PrismaEvangelismSection> {
    return this.prisma.evangelismSection.create<T>(args);
  }
  async updateEvangelismSection<T extends Prisma.EvangelismSectionUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.EvangelismSectionUpdateArgs>
  ): Promise<PrismaEvangelismSection> {
    return this.prisma.evangelismSection.update<T>(args);
  }
  async deleteEvangelismSection<T extends Prisma.EvangelismSectionDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.EvangelismSectionDeleteArgs>
  ): Promise<PrismaEvangelismSection> {
    return this.prisma.evangelismSection.delete(args);
  }
}
