/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { GrowthSection } from "./GrowthSection";
import { GrowthSectionCountArgs } from "./GrowthSectionCountArgs";
import { GrowthSectionFindManyArgs } from "./GrowthSectionFindManyArgs";
import { GrowthSectionFindUniqueArgs } from "./GrowthSectionFindUniqueArgs";
import { DeleteGrowthSectionArgs } from "./DeleteGrowthSectionArgs";
import { GrowthSectionService } from "../growthSection.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => GrowthSection)
export class GrowthSectionResolverBase {
  constructor(
    protected readonly service: GrowthSectionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "GrowthSection",
    action: "read",
    possession: "any",
  })
  async _growthSectionsMeta(
    @graphql.Args() args: GrowthSectionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [GrowthSection])
  @nestAccessControl.UseRoles({
    resource: "GrowthSection",
    action: "read",
    possession: "any",
  })
  async growthSections(
    @graphql.Args() args: GrowthSectionFindManyArgs
  ): Promise<GrowthSection[]> {
    return this.service.growthSections(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => GrowthSection, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "GrowthSection",
    action: "read",
    possession: "own",
  })
  async growthSection(
    @graphql.Args() args: GrowthSectionFindUniqueArgs
  ): Promise<GrowthSection | null> {
    const result = await this.service.growthSection(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => GrowthSection)
  @nestAccessControl.UseRoles({
    resource: "GrowthSection",
    action: "delete",
    possession: "any",
  })
  async deleteGrowthSection(
    @graphql.Args() args: DeleteGrowthSectionArgs
  ): Promise<GrowthSection | null> {
    try {
      return await this.service.deleteGrowthSection(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
