/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { GivingSection } from "./GivingSection";
import { GivingSectionCountArgs } from "./GivingSectionCountArgs";
import { GivingSectionFindManyArgs } from "./GivingSectionFindManyArgs";
import { GivingSectionFindUniqueArgs } from "./GivingSectionFindUniqueArgs";
import { DeleteGivingSectionArgs } from "./DeleteGivingSectionArgs";
import { GivingSectionService } from "../givingSection.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => GivingSection)
export class GivingSectionResolverBase {
  constructor(
    protected readonly service: GivingSectionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "GivingSection",
    action: "read",
    possession: "any",
  })
  async _givingSectionsMeta(
    @graphql.Args() args: GivingSectionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [GivingSection])
  @nestAccessControl.UseRoles({
    resource: "GivingSection",
    action: "read",
    possession: "any",
  })
  async givingSections(
    @graphql.Args() args: GivingSectionFindManyArgs
  ): Promise<GivingSection[]> {
    return this.service.givingSections(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => GivingSection, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "GivingSection",
    action: "read",
    possession: "own",
  })
  async givingSection(
    @graphql.Args() args: GivingSectionFindUniqueArgs
  ): Promise<GivingSection | null> {
    const result = await this.service.givingSection(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => GivingSection)
  @nestAccessControl.UseRoles({
    resource: "GivingSection",
    action: "delete",
    possession: "any",
  })
  async deleteGivingSection(
    @graphql.Args() args: DeleteGivingSectionArgs
  ): Promise<GivingSection | null> {
    try {
      return await this.service.deleteGivingSection(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
