/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  HelpSupportSection as PrismaHelpSupportSection,
} from "@prisma/client";

export class HelpSupportSectionServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.HelpSupportSectionCountArgs, "select">
  ): Promise<number> {
    return this.prisma.helpSupportSection.count(args);
  }

  async helpSupportSections<T extends Prisma.HelpSupportSectionFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.HelpSupportSectionFindManyArgs>
  ): Promise<PrismaHelpSupportSection[]> {
    return this.prisma.helpSupportSection.findMany<Prisma.HelpSupportSectionFindManyArgs>(
      args
    );
  }
  async helpSupportSection<T extends Prisma.HelpSupportSectionFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.HelpSupportSectionFindUniqueArgs>
  ): Promise<PrismaHelpSupportSection | null> {
    return this.prisma.helpSupportSection.findUnique(args);
  }
  async createHelpSupportSection<T extends Prisma.HelpSupportSectionCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.HelpSupportSectionCreateArgs>
  ): Promise<PrismaHelpSupportSection> {
    return this.prisma.helpSupportSection.create<T>(args);
  }
  async updateHelpSupportSection<T extends Prisma.HelpSupportSectionUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.HelpSupportSectionUpdateArgs>
  ): Promise<PrismaHelpSupportSection> {
    return this.prisma.helpSupportSection.update<T>(args);
  }
  async deleteHelpSupportSection<T extends Prisma.HelpSupportSectionDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.HelpSupportSectionDeleteArgs>
  ): Promise<PrismaHelpSupportSection> {
    return this.prisma.helpSupportSection.delete(args);
  }
}
