/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { BibleSection } from "./BibleSection";
import { BibleSectionCountArgs } from "./BibleSectionCountArgs";
import { BibleSectionFindManyArgs } from "./BibleSectionFindManyArgs";
import { BibleSectionFindUniqueArgs } from "./BibleSectionFindUniqueArgs";
import { DeleteBibleSectionArgs } from "./DeleteBibleSectionArgs";
import { BibleSectionService } from "../bibleSection.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => BibleSection)
export class BibleSectionResolverBase {
  constructor(
    protected readonly service: BibleSectionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "BibleSection",
    action: "read",
    possession: "any",
  })
  async _bibleSectionsMeta(
    @graphql.Args() args: BibleSectionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [BibleSection])
  @nestAccessControl.UseRoles({
    resource: "BibleSection",
    action: "read",
    possession: "any",
  })
  async bibleSections(
    @graphql.Args() args: BibleSectionFindManyArgs
  ): Promise<BibleSection[]> {
    return this.service.bibleSections(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => BibleSection, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "BibleSection",
    action: "read",
    possession: "own",
  })
  async bibleSection(
    @graphql.Args() args: BibleSectionFindUniqueArgs
  ): Promise<BibleSection | null> {
    const result = await this.service.bibleSection(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => BibleSection)
  @nestAccessControl.UseRoles({
    resource: "BibleSection",
    action: "delete",
    possession: "any",
  })
  async deleteBibleSection(
    @graphql.Args() args: DeleteBibleSectionArgs
  ): Promise<BibleSection | null> {
    try {
      return await this.service.deleteBibleSection(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
