/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { FamilySection } from "./FamilySection";
import { FamilySectionCountArgs } from "./FamilySectionCountArgs";
import { FamilySectionFindManyArgs } from "./FamilySectionFindManyArgs";
import { FamilySectionFindUniqueArgs } from "./FamilySectionFindUniqueArgs";
import { DeleteFamilySectionArgs } from "./DeleteFamilySectionArgs";
import { FamilySectionService } from "../familySection.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => FamilySection)
export class FamilySectionResolverBase {
  constructor(
    protected readonly service: FamilySectionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "FamilySection",
    action: "read",
    possession: "any",
  })
  async _familySectionsMeta(
    @graphql.Args() args: FamilySectionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [FamilySection])
  @nestAccessControl.UseRoles({
    resource: "FamilySection",
    action: "read",
    possession: "any",
  })
  async familySections(
    @graphql.Args() args: FamilySectionFindManyArgs
  ): Promise<FamilySection[]> {
    return this.service.familySections(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => FamilySection, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "FamilySection",
    action: "read",
    possession: "own",
  })
  async familySection(
    @graphql.Args() args: FamilySectionFindUniqueArgs
  ): Promise<FamilySection | null> {
    const result = await this.service.familySection(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => FamilySection)
  @nestAccessControl.UseRoles({
    resource: "FamilySection",
    action: "delete",
    possession: "any",
  })
  async deleteFamilySection(
    @graphql.Args() args: DeleteFamilySectionArgs
  ): Promise<FamilySection | null> {
    try {
      return await this.service.deleteFamilySection(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
