/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { HomeScreenService } from "../homeScreen.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { HomeScreenCreateInput } from "./HomeScreenCreateInput";
import { HomeScreen } from "./HomeScreen";
import { HomeScreenFindManyArgs } from "./HomeScreenFindManyArgs";
import { HomeScreenWhereUniqueInput } from "./HomeScreenWhereUniqueInput";
import { HomeScreenUpdateInput } from "./HomeScreenUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class HomeScreenControllerBase {
  constructor(
    protected readonly service: HomeScreenService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: HomeScreen })
  @nestAccessControl.UseRoles({
    resource: "HomeScreen",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createHomeScreen(
    @common.Body() data: HomeScreenCreateInput
  ): Promise<HomeScreen> {
    return await this.service.createHomeScreen({
      data: data,
      select: {
        createdAt: true,
        dailyVerse: true,
        id: true,
        quickLinks: true,
        updatedAt: true,
        welcomeMessage: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [HomeScreen] })
  @ApiNestedQuery(HomeScreenFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "HomeScreen",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async homeScreens(@common.Req() request: Request): Promise<HomeScreen[]> {
    const args = plainToClass(HomeScreenFindManyArgs, request.query);
    return this.service.homeScreens({
      ...args,
      select: {
        createdAt: true,
        dailyVerse: true,
        id: true,
        quickLinks: true,
        updatedAt: true,
        welcomeMessage: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: HomeScreen })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HomeScreen",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async homeScreen(
    @common.Param() params: HomeScreenWhereUniqueInput
  ): Promise<HomeScreen | null> {
    const result = await this.service.homeScreen({
      where: params,
      select: {
        createdAt: true,
        dailyVerse: true,
        id: true,
        quickLinks: true,
        updatedAt: true,
        welcomeMessage: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: HomeScreen })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HomeScreen",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateHomeScreen(
    @common.Param() params: HomeScreenWhereUniqueInput,
    @common.Body() data: HomeScreenUpdateInput
  ): Promise<HomeScreen | null> {
    try {
      return await this.service.updateHomeScreen({
        where: params,
        data: data,
        select: {
          createdAt: true,
          dailyVerse: true,
          id: true,
          quickLinks: true,
          updatedAt: true,
          welcomeMessage: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: HomeScreen })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HomeScreen",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteHomeScreen(
    @common.Param() params: HomeScreenWhereUniqueInput
  ): Promise<HomeScreen | null> {
    try {
      return await this.service.deleteHomeScreen({
        where: params,
        select: {
          createdAt: true,
          dailyVerse: true,
          id: true,
          quickLinks: true,
          updatedAt: true,
          welcomeMessage: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
